Add party guide to resource
zalando/zalando.github.io pull request #277
Opened 2018-09-27 12:52 UTC by hpdang

2018-09-27 12:53 UTC, perploug commented on _docs/resources/how-to-organize-release-party.md
> +index: 1
make sure the navigation index is correct

2018-09-27 13:27 UTC, perploug requested changes

2018-09-27 13:27 UTC, perploug commented on _docs/resources/how-to-organize-release-party.md
> +For registration, you could use Google Form, Google Calendar, or open source solution [Eventyay](https://eventyay.com/).
Have you checked if Eventyay is something Zalandos can use - if its a service - then we need consider GDPR

2018-09-27 13:27 UTC, perploug commented on _docs/resources/how-to-organize-release-party.md
> +* Create a facebook event including your sign-up form.
should we include meetup.com in this list ?

2018-09-27 13:27 UTC, perploug commented on _docs/resources/how-to-organize-release-party.md
> +### Step 3: Lockdown venue, logistics, budget
I think lockdown refers to security - Should probably be "Secure venue, logistics and budget"

2018-10-04 13:19 UTC, hpdang commented on _docs/resources/how-to-organize-release-party.md
> +For registration, you could use Google Form, Google Calendar, or open source solution [Eventyay](https://eventyay.com/).
@perploug it is an open source solution, people can set it up on their own server

2018-10-04 13:19 UTC, hpdang commented
@perploug I created a new PR including this article, can we close this?

2018-10-04 13:20 UTC, hpdang commented on _docs/resources/how-to-organize-release-party.md
> +* Create a facebook event including your sign-up form.
only meetup organizer can publish a meetup. Organizers pay a fee. I already included this information on the promotion channels article

2018-10-04 13:21 UTC, closed without merging