jan-updates
zalando/zalando.github.io pull request #397
Opened 2019-02-12 18:54 UTC by hpdang

Signed-off-by: hpdang <dhppat@gmail.com>

2019-02-13 08:02 UTC, perploug commented on _posts/2019-02-07-jan-updates.md
> +## Project Highlights
I think the harassment policy blogpost should also be added to the january review

2019-02-13 09:19 UTC, perploug requested changes
reads well, besides the single comment I think it looks ready to publish

2019-02-18 14:27 UTC, perploug commented
Hey @hpdang - any updates on this?

2019-02-19 15:14 UTC, hpdang commented
@perploug please review

2019-02-20 10:55 UTC, perploug submitted a review, later dismissed

2019-02-20 10:56 UTC, merged